### ISSUE TITLE
[backend] 유저의 상태 업데이트 (socket)

### ISSUE THREAD

**Issue by Hyoj-Kim** [GunGonGamLeeLee/ft_transcendence#114]
namespace: dm
- [x] handleConnection, handleDisconnect
- [x] handleConnection에서 auth token 검증 후 `dm${uid}` room 자동 생성

**Comment by jpham005** [comment]
이거 혹시 이름 변경 됐을때도 업데이트 가능할까요

업데이트 할때 이름이랑 상태 같이 보내주면 될 것 같아요
