### ISSUE TITLE
[backend] 채팅방 안에 들어가는 순간 해야하는 것들 - api 명세 포함

### ISSUE THREAD

**Issue by 42mypark** [GunGonGamLeeLee/ft_transcendence#115]
- [x] 1. 비밀번호 인증.(없으면 pass)

- [x] 2. 채널 접속리스트, 음소거 리스트, 밴 리스트 리턴.

**Comment by 42mypark** [comment]
1. 비밀번호 인증.(없으면 pass)

Method: Post
body:
{
  chid: number;
  password: string; // encrypted? 4 글자?
}

return 201 or 40*

**Comment by 42mypark** [comment]
2. 채널 접속리스트, 음소거 리스트, 밴 리스트 리턴.

Method: Get

return {
  inChatRoom: UserDataType[],
  muteList: UserDataType[],
  banList: UserDataType[],
}

**Comment by 42mypark** [comment]
export interface UserDataType {
  uid: number;
  displayName: string;
  imgUri: string;
  rating: number;
  status: number;
}

**Comment by jpham005** [comment]
전에도 얘기 했지만, 채널 접속 리스트 제외한 나머지는 id만 주셔도 됩니다.

**Comment by jpham005** [comment]
chid 보단 channelId나 chatId정도면 어땠을까 싶네용. 아니면 roomId?
일단 chid로 맞췄습니다.
