### ISSUE TITLE
[frontend] 신규 유저로 프로필 설정 진입 시 에러

### ISSUE THREAD

**Issue by jpham005** [GunGonGamLeeLee/ft_transcendence#126]
그렇습니다.

번외로 간혹 소켓이 무한 커넥팅 대기 상태에 빠지는데, (아마 서버 재시작이나 새로고침 시 다시 렌더링 하는 과정에서 문제가 있지 않을까 싶습니다...)
useEffect cleanup을 잘 해줘야 하는건지... 어렵네요.

일단 새로고침 다시 하면 접속은 되는데, 이유를 알아보긴 해야할 것 같아요

**Comment by jpham005** [comment]
+ 권한 없는 유저가 채팅방 진입할때? 아마 throw 관련 아닐까용

**Comment by jpham005** [comment]
일단 소켓으로 인한 문제인지 확인을 해봐야 합니다...

**Comment by 42mypark** [comment]
소켓 useEffect 에서 on  하시고 off(cleanUp) 해주셨나요?

**Comment by jpham005** [comment]
일단 오늘은 데이터 넘어오는 버그 때문에 계속 disconnect - reconnect 하는 문제가 있었기 때문에...
내일 다시 봐야 알 것 같아요

**Comment by jpham005** [comment]
일단 이 문제가 사파리에서만 발생 중 입니다.
왜그런진 모르겠네요...

**Comment by jpham005** [comment]
recoil debug 해주는 부분과 문제가 있었던 것 같습니다.
해당 기능을 완성단계에서만 제거하면 될 것 같고, 그와 별개로 개발중엔 에러 발생 시 새로고침 한번만 해주면 됩니다.
