### ISSUE TITLE
[backend] dm/status로 리턴하는 로직 에러

### ISSUE THREAD

**Issue by jpham005** [GunGonGamLeeLee/ft_transcendence#128]
유저가 처음 접속한 경우, 
app gateway에서는 dm/status로 배열을 보냅니다.

반면,
state update를 해야하는 경우,
dm gateway 에서 업데이트된 친구만 보내고 있어요.

제 생각엔 update를 forEach 로 하나씩 보내지 말고,
map으로 필요한 데이터만 뽑아서 보낸다던지 (friendList 보낼땐 데이터 선별 작업도 없어서 문제입니다.) 해야할 것 같습니다.

제가 직접 수정 가능한 부분이긴 한데, 수정이 없다면 내일 고치도록 하겠습니다..

아 그리고 아까 든 생각인데 friend 처음 받아오는건 http로 하는거 있지 않나요 ㅋㅋ 그냥 그걸 뻬버리면 되겠네요

**Comment by 42mypark** [comment]
뭐가 문제인지 파악했습니다. 같은 이벤트에 대해 다른 방식으로 보내고 있네요.

아 그리고 아까 든 생각인데 friend 처음 받아오는건 http로 하는거 있지 않나요 ㅋㅋ 그냥 그걸 뻬버리면 되겠네요
-> 이 부분에 대해서는 이미 테스트한 로직 굳이 수정해야 싶긴합니다.
-> 지금 app.gateway 에 있는 친구 목록가는 로직이 삭제되어야 맞는 것 같네요.
-> 아래 코드 부분.
```
    // 친구들의 상태 가져오기
    const friendList = await this.dmService.getFriendList(client.data.uid);
    this.server.to(client.id).emit('dm/status', friendList);
```

제 생각엔 update를 forEach 로 하나씩 보내지 말고,
-> 이 부분은 나를 팔로우한 유저한테 각각 보내는 거라 forEach로 보내는 게 맞습니다.
-> forEach를 쓰지말고 그냥 for문 쓰는 걸로 통일하는게 맞는 거 같네요.


위와 같이 처리하면, dm/status에 대한 이벤트가 하나가 되어 적절히 처리하실 수 있을 거 같네요.
혹시 바꿀 만한 부분 있나요?

**Comment by jpham005** [comment]
아 app.gateway로직을 지우자는 얘기였습니다. 말씀하신 방향이 맞아요!

그리고 따로 보내는게 맞는거라면, forEach 써서 안될 이유가 있나요?
for문이 어떤 점에서 좋은지 잘 모르겠어요.
for (value of list) 이런식으로 부르면 괜찮을 것 같긴 하네요

**Comment by 42mypark** [comment]
forEach써도 되긴하는데 제가 이미 for (value of list) 이런식으로 작성한 부분이 몇군데 있어서
통일할까 싶어서 그랬던 건데 굳이 상관 없긴 해요

**Comment by jpham005** [comment]
그러면 for문으로 하시죵
어차피 index로 돌리는 것만 아니면 괜찮다고 봐요
