### ISSUE TITLE
[backend] dm 주고 받기. - api 명세 포함

### ISSUE THREAD

**Issue by 42mypark** [GunGonGamLeeLee/ft_transcendence#130]
- [x] dm/msg (Socket api)
- [x] dm/log (Http api) // profile->dm 버튼 눌렀을 때, 1:1 대화->채팅방 눌렀을 때

**Comment by 42mypark** [comment]
direct message
eventName:  dm/msg,
body: 
{
  targetUid: number;
  msg: string;
}

**Comment by 42mypark** [comment]
- dm log 가져오기
api: dm/log
Method: Get
query: targetUid
```
return {
  logs: DmLogType[];
}
```

```
class DmLogType {
  
}
```

**Comment by 42mypark** [comment]
@jpham005  
나중에 확인해보시고 바꿀 점 있으면 말씀해주세요

**Comment by jpham005** [comment]
일단 채팅방쪽 끝나고 다시 보겠습니다

**Comment by jpham005** [comment]
아 display name 풀리퀘였군요 바로 확인해볼게요
