### ISSUE TITLE
[backend] 채팅방 관련 버그

### ISSUE THREAD

**Issue by jpham005** [GunGonGamLeeLee/ft_transcendence#142]
- [x] 모든 채팅방 목록을 가져오는 부분에서, mode를 넣지 않고 리턴하는 문제. db에서 꺼내올때 같이 가져오지 않는 것으로 보임

- [x] 채팅방 비밀번호 인증하는 부분에서, 비밀번호를 숫자로 강제하는 문제. 백엔드의 방 생성 로직에선 string을 받고 있는 것으로 보임.

- [x] 채팅방 생성 시 돌려받는건 roomId ('channel' + chid)이고, 그 이후 로직에서 사용하는건 chid인 문제.

**Comment by jpham005** [comment]
- [ ] 간혹 백엔드에서 index.html로 파일을 찾으려고 하는 부분 (백엔드 문제인지 아직 파악되지 않음)

![Image](https://user-images.githubusercontent.com/76723089/196037836-63337394-7bb4-49f5-b1fa-f56f564034b6.png)

**Comment by 42mypark** [comment]
코멘트로 달아주신건 저도 잘 몰라서 일단 넘어가긴 했는데 해결해야겠네요
