### ISSUE TITLE
[backend] roomId와 chid

### ISSUE THREAD

**Issue by jpham005** [GunGonGamLeeLee/ft_transcendence#146]
일단 비슷한 변수명으로 둘다 존재하니 헷갈리는 것도 문제고, chid를 내부적으로만 사용하는 것이 아니라, swagger까지 올라온건 문제가 있는 것 같습니다.
또, roomid와 chid를 api에서 같이 사용하다보니, 이것도 어느 한쪽으로 맞추는게 더 좋아보여요.

**Comment by 42mypark** [comment]
둘이 다른 개념이긴한데, 어쩌다보니 겹쳐버렸네요;
