### ISSUE TITLE
[backend] 소켓 부분 AuthGuard추가하기

### ISSUE THREAD

**Issue by 42mypark** [GunGonGamLeeLee/ft_transcendence#167]

**Comment by Hyoj-Kim** [comment]
- WsException 확인하기

**Comment by Hyoj-Kim** [comment]
exception을 catch 못하는 경우는 handleConnection 내에서 throw 했을 때!
Gateway의 handleConnection은 ExceptionFilter, Guards 둘 다 적용이 안된다고 합니다...
