### ISSUE TITLE
현재 프론트에서 필요로 하는 api 목록

### ISSUE THREAD

**Issue by jpham005** [GunGonGamLeeLee/ft_transcendence#59]
모든 uri는 임의로 작성한 것이고, 백엔드에서 생각중인 이름이 있다면 전달 부탁드립니다.
데이터 형식 또한 조정 가능하니 알려주세요.

Authorization: Bearer token 헤더는 기본적으로 들어가기 때문에 생략하겠습니다.

response의 경우, 실패 시 요청했던 값이 아닌 아무 값이나 주시면 됩니다.
단, 분기 처리가 필요하다고 생각되는 부분은 따로 알려주세요.

형식:
#### request
uri
method
headers
body
query

#### response
status
headers
body
query

---
### types

```ts
interface UserDataType {
  id: number,
  displayName: string,
  imgUri: string,
  rating: number,
  status: string (or number?)
}

interface RoomType {
  roomId: 1,
  title: 'example chat room title',
  owner: 'jeongble',
  userCount: 10,
  lock: true,
}
```

---
#### request
/users/me
Get
x
x
x
#### response
200
x
json object
```ts
interface ProfileType extends UserDataType
{
  mfaNeed: boolean
}
```
x

---
#### request
/users/friend
Get
x
x
x

#### response
200
x
json object array: Array\<UserDataType>
x

---
#### request
/users/rank
이하 /users/friend와 같음

---
####  request
/users/blocklist
이하 /users/friend와 같음

---
#### request
/users/follow
POST
Content-Type: application/json
json object
```ts
{
  id: number // 팔로우할 유저 id
}
```
x

#### response
201
x
x
x

---
#### request
/users/follow
DELETE
Content-Type: application/json
json object
```ts
{
  id: number
}
 ```
x

#### response
200
x
x
x

---
#### request
/users/block
POST
Content-Type: application/json
json object
``` ts
{
  id: number
}
```
x

#### response
/users/block
201
x
x
x

---
#### request
/users/block
DELETE
Content-Type: application/json
json object
```ts
{
  id: number
}
```
x

#### response
200
x
x
x

**Comment by 42mypark** [comment]
```
interface UserDataType {
  id: number,
  displayName: string,
  imgUri: string,
  rating: number,
  status: string (or number?) -> number
}
```

**Comment by 42mypark** [comment]
```

export enum UserStatus {
  OFFLINE,
  ONLINE,
  INGAME,
}
```

**Comment by 42mypark** [comment]
```
export enum UserRoleInChannel {
  OWNER,
  ADMIN,
  USER,
}
```

**Comment by 42mypark** [comment]
친구 추가 + 차단 해제 -> 친구 추가
차단 추가 + 친구 삭제 -> 차단 추가
db 로직 수정해야함
